version: '3.8'

services:
  app:
    image: my-little-pet:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["java", "-jar", "petServer-0.0.1-SNAPSHOT.jar"]